import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productName: "KILLER",
    price: 2000,
    description: "KL-1C Analog Watch - For Men",
    categoryName: "Mens",
    image:
      "https://rukminim2.flixcart.com/image/580/696/kqgyhe80/watch/k/m/j/kl-1c-killer-original-imag4gwsfjnbphhv.jpeg?q=50",
    latest: true,
    rate: 4.2,
    alt: "Killer watch",
    oldPrice: 3000,
    fastDelivery: true,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "POLO HUNTER",
    price: 1900,
    description: "PH-1331 Pack Of 2 Unique Combo Analog Watch - For Men",
    categoryName: "Mens",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/k5vcya80pkrrdj/watch/8/p/h/1331-polo-hunter-original-imafce58zt4bzsxq.jpeg?q=50",
    latest: true,
    rate: 4,
    alt: "POLO HUNTER",
    oldPrice: 3000,
    fastDelivery: false,
    quantity: 1,
    inStock: false,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "PROVOGUE",
    price: 749,
    description: "PRV-027B Analog Watch - For Men",
    categoryName: "Mens",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/ktszgy80/watch/k/q/o/prv-027b-provogue-men-original-imag72hfcyueqapj.jpeg?q=50",
    latest: true,
    rate: 3,
    alt: "PROVOGUE",
    oldPrice: 2199,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "LOIS CARON",
    price: 279,
    description: "LCS-8188 BLUE DIAL AND SILVER STRAP DAY & DATE FUNCTIONING WATCH FOR BOYS Analog Watch - For Men",
    categoryName: "Mens",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/k7z3afk0/watch/t/c/x/lcs-8188-lois-caron-original-imafq3k9ztzdkyhe.jpeg?q=50",
    latest: true,
    rate: 4.5,
    alt: "LOIS CARON",
    oldPrice: 1799,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Fastrack",
    price: 1865,
    description: "3240SM03 Analog Watch - For Men",
    categoryName: "Mens",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/kdoup3k0-0/watch/c/t/7/3240sm02-fastrack-original-imafujqsuwzbvsx9.jpeg?q=50",
    latest: true,
    rate: 4.3,
    alt: "Fastrack",
    oldPrice: 2195,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Dressberry",
    price: 649,
    description: "1185009 Analog Watch - For Women",
    categoryName: "Womens",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/l0fm07k0/watch/o/n/r/-original-imagc7vgga2wxegf.jpeg?q=50",
    latest: true,
    rate: 3.6,
    alt: "Dressberry",
    oldPrice: 2100,
    fastDelivery: true,
    quantity: 1,
    inStock: false,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Shunya",
    price: 169,
    description:
      "Black Mesh Magnetic Belt 2021 Quartz Black Dial Adjustable Luxurious Fashion Stylish Analog Watch - For Women",
    categoryName: "Womens",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/ksgehzk0/watch/q/5/t/1-black-mesh-magnetic-belt-2021-quartz-black-dial-adjustable-original-imag6yuvyu8bas7h.jpeg?q=50",
    latest: true,
    rate: 3,
    alt: "Shunya",
    oldPrice: 1499,
    fastDelivery: false,
    quantity: 1,
    inStock: false,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Varni Retail",
    price: 259,
    description:
      "Attrective Rosegold And Silver Combo Wrist Analog Watch girls and woman combo watches Analog Watch - For Women",
    categoryName: "Womens",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/k0e66q80/watch/s/g/m/attrective-rosegold-and-silver-combo-wrist-analog-watch-varni-original-imafk4vtvuaqugbm.jpeg?q=50",
    latest: true,
    rate: 4,
    alt: "Varni Retail",
    oldPrice: 1499,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Dressberry",
    price: 999,
    description:
      "1487944 Analog Watch - For Women",
    categoryName: "Womens",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/kz3118w0/watch/h/q/b/-original-imagb679gqwebqbj.jpeg?q=50",
    latest: true,
    rate: 3.2,
    alt: "Dressberry",
    oldPrice: 2799,
    fastDelivery: true,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Fastrack",
    price: 1440,
    description:
      "68007PP02 Trendies Analog Watch - For Women",
    categoryName: "Womens",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/k4rcmfk0pkrrdj/watch-refurbished/q/5/6/c-68007pp02-fastrack-original-imafcg3zkchh5fb5.jpeg?q=50",
    latest: true,
    rate: 3.1,
    alt: "Fastrack",
    oldPrice: 1695,
    fastDelivery: true,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "hala",
    price: 1600,
    description:
      "VKRDGC810 Multi-Function Stylish Sports Militaries New Arrival Silicon Strap Digital Pack of 2 Combo Men And Boys Hot And Cool Best Quality Evers New Year Fashion Sports Digital Stylish Lights New Generation Amazing Look Cool Style Digital Watch Digital Watch - For Boys",
    categoryName: "Boys",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/krz97rk0/watch/a/d/u/abx1017-gents-green-solitary-camouflage-pattern-new-generation-original-imag5n3muvcb3xtv.jpeg?q=50",
    latest: true,
    rate: 2.1,
    alt: "hala watch",
    oldPrice: 3000,
    fastDelivery: true,
    quantity: 1,
    inStock: false,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "SKMEI",
    price: 353,
    description: "Attractive Blue Men Sport Military Series Analogue Digital Blue Black 1155BLU Waterproof Chorono Analog-Digital Watch - For Boys",
    categoryName: "Boys",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/k55n0y80/watch/z/c/g/blue-skm-1155-blue-hatin-original-imafksghmfh9jyjv.jpeg?q=50",
    latest: true,
    rate: 2,
    alt: "SKMEI",
    oldPrice: 2199,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Praizy",
    price: 159,
    description: "New Modish Mahadev Analog Watch - For Boys",
    categoryName: "Boys",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/l09w8sw0/watch/a/u/h/1-new-modish-mahadev-praizy-boys-original-imagc3apbnzjxz3u.jpeg?q=50",
    latest: true,
    rate: 4.1,
    alt: "Praizy",
    oldPrice: 2199,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "POLO HUNTER",
    price: 253,
    description: "KL-1C Analog Watch - For Men",
    categoryName: "Boys",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/kabe9ow0pkrrdj/watch/w/h/w/9032-polo-hunter-original-imafsfhftyrf3azn.jpeg?q=50",
    latest: true,
    rate: 2,
    alt: "POLO HUNTER",
    oldPrice: 2199,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Happy Khajana",
    price: 253,
    description: "KJR_571 King Blue Matt Finish And One Attractive Analog Watch - For Boys",
    categoryName: "Boys",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/kon887k0/watch/t/r/c/kjr-571-king-blue-happy-khajana-original-imag32adhbxnfqfe.jpeg?q=50",
    latest: true,
    rate: 2,
    alt: "Happy Khajana",
    oldPrice: 1999,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Rizzly",
    price: 147,
    description: "118-Girls Stylish Analog Analog Watch - For Girls",
    categoryName: "Girls",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/k6gsk280/watch/h/r/y/118-shiny-and-slim-rizzly-original-imafzp58juqtawzd.jpeg?q=50",
    latest: true,
    rate: 1.6,
    alt: "Rizzly",
    oldPrice: 1999,
    fastDelivery: true,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Daniel Jubile",
    price: 187,
    description:
      "Luxury Jubile Women Silver girls watch for women watches girls stylish ladies watches Silver Black Color Analog Watch - For Girls",
    categoryName: "Girls",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/kyg5zm80/watch/d/0/h/luxury-jubile-women-silver-daniel-jubile-girls-original-imagaz9ax8tzfqhz.jpeg?q=50",
    latest: true,
    rate: 1,
    alt: "Daniel Jubile",
    oldPrice: 2199,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "LAXMO",
    price: 255,
    description:
      "butterfly black&pink New Branded & Stylish Buterfly Shape With Diamond Fab Combo Analog Watch - For Girls",
    categoryName: "Girls",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/ktaeqvk0/watch/d/5/r/2-butterfly-black-pink-laxmo-girls-original-imag6z3fxtg48nff.jpeg?q=50",
    latest: true,
    rate: 3,
    alt: "LAXMO",
    oldPrice: 999,
    fastDelivery: false,
    quantity: 1,
    inStock: false,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Just like",
    price: 387,
    description:
      "Designer Multi Colorful Dial Leathers Strap (Casual+PartyWear+Formal) Pack Of 3 combo watch For Girls And Women Wrist Watches Analog Watch - For Girls",
    categoryName: "Girls",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/kidgnm80-0/watch/x/2/0/designer-multi-colorful-dial-leathers-strap-casual-partywear-original-imafy6ngqxq4gnbm.jpeg?q=50",
    latest: true,
    rate: 3.4,
    alt: "Just like",
    oldPrice: 1599,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
  {
    _id: uuid(),
    productName: "Daniel Jubile",
    price: 199,
    description:
      "Magnet Strap Girls Women 4-Point 369 Rishtey Red Magnetic Chain magnet strap mash hand watch girls watch for women gift Red Analog Watch - For Girls",
    categoryName: "Girls",
    image:
      "https://rukminim2.flixcart.com/image/880/1056/kbs9k7k0/watch/t/m/m/indian-rishtey-present-all-diamond-red-daniel-jubile-original-imaft29p4ebbmzfk.jpeg?q=50",
    latest: true,
    rate: 3.9,
    alt: "Daniel Jubile",
    oldPrice: 1499,
    fastDelivery: false,
    quantity: 1,
    inStock: true,
    discount: Math.floor(Math.random() * 100),
  },
];
